# example to use in the https://github.com/rgl/gitlab-ci-vagrant environment.

# XXX matrix support in gitlab-runner is somewhat lacking a way to create independent flows.
#     see https://gitlab.com/gitlab-org/gitlab/-/issues/254821

.matrix:
  tags:
    - ${TAG}
    - shell
  parallel:
    matrix:
      - TAG: [windows, linux]

build:
  extends: .matrix
  script:
    - ./build.ps1 build
  artifacts:
    expire_in: 1 week
    paths:
      - '*/bin'

test:
  extends: .matrix
  script:
    - ./build.ps1 test
  artifacts:
    name: test-reports
    when: always
    expire_in: 1 week
    paths:
      - '*/TestResults/*-report.*'
    reports:
      # NB these are displayed in the Pipeline (Tests tab) and Merge Request pages.
      junit: '*/TestResults/TestResults.xml'
  needs:
    - build
