name: Build
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.405'
      - name: Install dependencies
        run: ./build.ps1 dependencies
      - name: Build
        run: ./build.ps1 build
      - name: Test
        run: ./build.ps1 test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            */bin/Release/*.nupkg
            */TestResults/*-report.*
            */TestResults/TestResults.xml
