name: Build
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.101'
      - name: Install dependencies
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.0.0
      - name: Build
        run: ./build.ps1 build
      - name: Test
        run: ./build.ps1 test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            */bin/Release/*.nupkg
            */TestResults/*-report.*
            */TestResults/TestResults.xml
